### Generated by ConfigEditor ###
import sys
import os.path
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_BASE','FWLitePython/cmsswScripts'))))
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_RELEASE_BASE','FWLitePython/cmsswScripts'))))
### ------------------------- ###

from runPATwithPFBReco_cfg import *

### Generated by ConfigEditor ###
if hasattr(process,'resetHistory'): process.resetHistory()
### ------------------------- ###
#################################
#################################
trigger = 'HLT_IsoMu24_eta2p1_v*'
triggersUsedForAnalysis = { 'singleMuon':{
		'data' : {trigger:[190456,193621]},
		'mc' : trigger
	}
}
####trigger########
process.triggerCheck = cms.EDFilter("TriggerResultsFilter",
    l1tIgnoreMask = cms.bool(False),
    l1tResults = cms.InputTag(""),
    l1techIgnorePrescales = cms.bool(False),
    hltResults = cms.InputTag("TriggerResults","","HLT"),
    triggerConditions = cms.vstring(trigger),
    throw = cms.bool(False),
    daqPartitions = cms.uint32(1)
)
process.source.fileNames = ['/store/data/Run2012A/SingleMu/AOD/22Jan2013-v1/20000/002F5062-346F-E211-BF00-1CC1DE04DF20.root']
process.p += process.triggerCheck
