### Generated by ConfigEditor ###
import sys
import os.path
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_BASE','FWLitePython/cmsswScripts'))))
sys.path.append(os.path.abspath(os.path.expandvars(os.path.join('$CMSSW_RELEASE_BASE','FWLitePython/cmsswScripts'))))
### ------------------------- ###

from runPATwithPFBReco_cfg import *

### Generated by ConfigEditor ###
if hasattr(process,'resetHistory'): process.resetHistory()
### ------------------------- ###
#################################
#################################

####trigger########
process.triggerCheck = cms.EDFilter("TriggerResultsFilter",
    l1tIgnoreMask = cms.bool(False),
    l1tResults = cms.InputTag(""),
    l1techIgnorePrescales = cms.bool(False),
    hltResults = cms.InputTag("TriggerResults","","HLT"),
    triggerConditions = cms.vstring('HLT_IsoMu24_eta2p1_v*'),
    throw = cms.bool(False),
    daqPartitions = cms.uint32(1)
)

process.p += process.triggerCheck
